# fly.toml app configuration file generated for bot-telegram-zie on 2026-10-09T06:38:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-telegram-zie'
primary_region = 'ams'

[build]

[processes]
  app = 'python bot.py'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
